version: "3.8"
services:

  db:
    container_name: "mariadb"
    image: "mariadb:10.6.16"
    command: ["mysqld", "--sql_mode=", "--default_time_zone=America/Sao_Paulo"]
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
    ports:
      - 3306:3306
    volumes:
      - ./conf/db:/var/lib/mysql

  php:
    container_name: "php-apache"
    build:
      context: .
    volumes:
      - ./www/:/var/www/html/
    ports:
      - 80:80
      - 443:443
    links:
      - db
    depends_on:
      - db